[tool.poetry]
name = "course-work-4"
version = "0.1.0"
description = ""
authors = ["Evgeniya <osipova.dr17@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
